import type { CollectionDefinition } from '../../domain/models';

export const HADITH_UNLOCKED_COLLECTIONS: readonly CollectionDefinition[] = [
  {id:'ibnrajab50',name:"Jami' Al-Ulum wal-Hikam",providerId:'hadith-unlocked',author:'Abd Al-Rahman Ibn Ahmad Ibn Rajab Al-Hanbali'},
  {id:'riyad',name:'Riyad As-Salihin',providerId:'hadith-unlocked',author:'Abu Zakariyya Yahya Ibn Sharaf Al-Nawawi'},
  {id:'adab',name:'Al-Adab Al-Mufrad',providerId:'hadith-unlocked',author:'Abu Abdullah Muhammad Ibn Ismail Al-Bukhari'},
  {id:'shamail',name:"Ash-Shama'il Al-Muhammadiyyah",providerId:'hadith-unlocked',author:'Abu Isa Muhammad Ibn Isa Al-Tirmidhi'},
  {id:'lulu-marjan',name:"Al-Lu'lu' wal-Marjan",providerId:'hadith-unlocked',author:'Muhammad Fuad Abd Al-Baqi'},
  {id:'bukhari',name:'Sahih Al-Bukhari',providerId:'hadith-unlocked',author:'Muhammad Ibn Ismail Al-Bukhari'},
  {id:'muslim',name:'Sahih Al-Muslim',providerId:'hadith-unlocked',author:'Muslim Ibn Al-Hajjaj'},
  {id:'abudawud',name:'Sunan Abi Dawud',providerId:'hadith-unlocked',author:'Abu Dawud Sulayman Ibn Ishaq Al-Sijistani'},
  {id:'tirmidhi',name:'Sunan At-Tirmidhi',providerId:'hadith-unlocked',author:'Abu Isa Muhammad Ibn Isa Al-Tirmidhi'},
  {id:'nasai',name:"Sunan An-Nasa'i",providerId:'hadith-unlocked',author:'Abu Abd Al-Rahman Ahmad Al-Nasai'},
  {id:'ibnmajah',name:'Sunan Ibn Majah',providerId:'hadith-unlocked',author:'Abu Abdullah Muhammad Ibn Yazid Ibn Majah Al-Qazwini'},
  {id:'darimi',name:'Sunan Ad-Darimi',providerId:'hadith-unlocked',author:'Abu Muhammad Abdullah Ibn Abd Al-Rahman Al-Darimi Al-Samarqandi'},
  {id:'ahmad',name:'Musnad Ahmad',providerId:'hadith-unlocked',author:'Abu Abdullah Ahmad Ibn Hanbal'},
  {id:'malik',name:'Muwatta Malik',providerId:'hadith-unlocked',author:'Malik Ibn Anas'},
  {id:'hakim',name:'Al-Mustadrak',providerId:'hadith-unlocked',author:'Abu Abdullah Muhammad Ibn Abdullah Al-Hakim Al-Naysaburi'},
  {id:'ibnhibban',name:'Sahih Ibn Hibban',providerId:'hadith-unlocked',author:'Muhammad Ibn Hibban Al-Busti'},
  {id:'ibnkhuzaymah',name:'Sahih Ibn Khuzaymah',providerId:'hadith-unlocked',author:'Abu Bakr Muhammad Ibn Ishaq Ibn Khuzaymah'},
  {id:'bazzar',name:'Musnad Al-Bazzar',providerId:'hadith-unlocked',author:'Abu Bakr Ahmad Ibn Amr Al-Bazzar'},
  {id:'daraqutni',name:'Sunan Ad-Daraqutni',providerId:'hadith-unlocked',author:'Abu Al-Hasan Ali Ibn Umar Al-Daraqutni'},
  {id:'abdalrazzaq',name:'Musannaf Abd Ar-Razzaq',providerId:'hadith-unlocked',author:'Abu Bakr Abd Al-Razzaq Ibn Hammam Al-Sanani'},
  {id:'ibnabishaybah',name:'Musannaf Ibn Abi Shaybah',providerId:'hadith-unlocked',author:'Abu Bakr Abdullah Ibn Muhammad Ibn Abu Shaybah'},
  {id:'nasai-kubra',name:"As-Sunan Al-Kubra (An-Nasa'i)",providerId:'hadith-unlocked',author:'Abu Abd Al-Rahman Ahmad Al-Nasai'},
  {id:'bayhaqi',name:'As-Sunan Al-Kubra (Al-Bayhaqi)',providerId:'hadith-unlocked',author:'Abu Bakr Ahmad Ibn Al-Husayn Al-Bayhaqi'},
  {id:'tayalisi',name:'Musnad At-Tayalisi',providerId:'hadith-unlocked',author:'Abu Dawud Sulayman Ibn Dawud Al-Tayalisi'},
  {id:'abuyaala',name:"Musnad Abu Ya'la",providerId:'hadith-unlocked',author:'Abu Yaala Ahmad Ibn Ali Al-Mawsili'},
  {id:'matalib',name:'Al-Matalib Al-Aliya',providerId:'hadith-unlocked',author:'Ibn Hajar Al-Asqalani'},
  {id:'tabarani-saghir',name:"Al-Mu'jam As-Saghir",providerId:'hadith-unlocked',author:'Abu Al-Qasim Sulayman Ibn Ahmad Al-Tabarani'},
  {id:'tabarani-awsat',name:"Al-Mu'jam Al-Awsat",providerId:'hadith-unlocked',author:'Abu Al-Qasim Sulayman Ibn Ahmad Al-Tabarani'},
  {id:'tabarani',name:"Al-Mu'jam Al-Kabir",providerId:'hadith-unlocked',author:'Abu Al-Qasim Sulayman Ibn Ahmad Al-Tabarani'},
  {id:'suyuti',name:'Suyuti',providerId:'hadith-unlocked',author:'Jalal Al-Din Abd Al-Rahman Ibn Abi Bakr Al-Suyuti'},
];
